# Generated by Django 6.0.6 on 2026-06-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subscriber', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
